/**
 * Builds supabase/seed.sql from Recipes.json and supabase/data/meal_types.json.
 * Run: npx tsx scripts/build-seed.ts
 * The seed is loaded by `supabase db reset` locally and can be run once against the cloud project.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { normalizeRecipe, type RawRecipe } from '../src/planner/recipes.js';

const root = (p: string) => fileURLToPath(new URL(`../../${p}`, import.meta.url));

const raw: RawRecipe[] = JSON.parse(readFileSync(root('Recipes.json'), 'utf8'));
const mealTypes: Record<string, string[]> = JSON.parse(readFileSync(root('supabase/data/meal_types.json'), 'utf8'));

const rows = raw.map((r) => {
  const recipe = normalizeRecipe(r);
  const types = mealTypes[r.recipeName];
  if (!types) throw new Error(`No meal types for "${r.recipeName}"`);
  return {
    id: recipe.id,
    name: recipe.name,
    cost: recipe.cost,
    skill: recipe.skill,
    minutes: recipe.minutes,
    diets: recipe.diets,
    meal_types: types,
    ingredients: r.ingredients, // keep quantity/unit/name structured for pantry matching
    steps: r.steps,
  };
});

const json = JSON.stringify(rows);
if (json.includes('$seed$')) throw new Error('Seed data contains the dollar-quote tag');

const sql = `-- Generated by api/scripts/build-seed.ts. Do not edit by hand.
insert into public.recipes (id, name, cost, skill, minutes, diets, meal_types, ingredients, steps)
select id, name, cost, skill, minutes, diets, meal_types, ingredients, steps
from jsonb_to_recordset($seed$${json}$seed$::jsonb)
  as x(id text, name text, cost text, skill text, minutes integer, diets text[], meal_types text[], ingredients jsonb, steps text[])
on conflict (id) do update set
  name = excluded.name, cost = excluded.cost, skill = excluded.skill, minutes = excluded.minutes,
  diets = excluded.diets, meal_types = excluded.meal_types, ingredients = excluded.ingredients, steps = excluded.steps;
`;

writeFileSync(root('supabase/seed.sql'), sql);
console.log(`Wrote ${rows.length} recipes to supabase/seed.sql`);
